workspace:
  base: /go
  path: src/github.com/abaeve/pricing-fetcher

pipeline:
  build:
    image: golang:1.8
    commands:
      - go get -t -v ./...
      - go get github.com/mattn/goveralls
      - goveralls -service=drone.io -ignore=main.go,mocks/worker_mocks.go,fetching/fetcher_mocks.go,mocks/broker_mocks.go -repotoken=${REPOTOKEN}