// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/abaeve/pricing-fetcher/fetching (interfaces: OrderFetcher,HistoryFetcher)

package mock_fetching

import (
	v1 "github.com/antihax/goesi/v1"
	gomock "github.com/golang/mock/gomock"
	http "net/http"
)

// Mock of OrderFetcher interface
type MockOrderFetcher struct {
	ctrl     *gomock.Controller
	recorder *_MockOrderFetcherRecorder
}

// Recorder for MockOrderFetcher (not exported)
type _MockOrderFetcherRecorder struct {
	mock *MockOrderFetcher
}

func NewMockOrderFetcher(ctrl *gomock.Controller) *MockOrderFetcher {
	mock := &MockOrderFetcher{ctrl: ctrl}
	mock.recorder = &_MockOrderFetcherRecorder{mock}
	return mock
}

func (_m *MockOrderFetcher) EXPECT() *_MockOrderFetcherRecorder {
	return _m.recorder
}

func (_m *MockOrderFetcher) GetMarketsRegionIdOrders(_param0 string, _param1 int32, _param2 map[string]interface{}) ([]v1.GetMarketsRegionIdOrders200Ok, *http.Response, error) {
	ret := _m.ctrl.Call(_m, "GetMarketsRegionIdOrders", _param0, _param1, _param2)
	ret0, _ := ret[0].([]v1.GetMarketsRegionIdOrders200Ok)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

func (_mr *_MockOrderFetcherRecorder) GetMarketsRegionIdOrders(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetMarketsRegionIdOrders", arg0, arg1, arg2)
}

// Mock of HistoryFetcher interface
type MockHistoryFetcher struct {
	ctrl     *gomock.Controller
	recorder *_MockHistoryFetcherRecorder
}

// Recorder for MockHistoryFetcher (not exported)
type _MockHistoryFetcherRecorder struct {
	mock *MockHistoryFetcher
}

func NewMockHistoryFetcher(ctrl *gomock.Controller) *MockHistoryFetcher {
	mock := &MockHistoryFetcher{ctrl: ctrl}
	mock.recorder = &_MockHistoryFetcherRecorder{mock}
	return mock
}

func (_m *MockHistoryFetcher) EXPECT() *_MockHistoryFetcherRecorder {
	return _m.recorder
}

func (_m *MockHistoryFetcher) GetMarketsRegionIdHistory(_param0 int32, _param1 int32, _param2 map[string]interface{}) ([]v1.GetMarketsRegionIdHistory200Ok, *http.Response, error) {
	ret := _m.ctrl.Call(_m, "GetMarketsRegionIdHistory", _param0, _param1, _param2)
	ret0, _ := ret[0].([]v1.GetMarketsRegionIdHistory200Ok)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

func (_mr *_MockHistoryFetcherRecorder) GetMarketsRegionIdHistory(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetMarketsRegionIdHistory", arg0, arg1, arg2)
}
