// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/goinggo/work (interfaces: Worker)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Worker interface
type MockWorker struct {
	ctrl     *gomock.Controller
	recorder *_MockWorkerRecorder
}

// Recorder for MockWorker (not exported)
type _MockWorkerRecorder struct {
	mock *MockWorker
}

func NewMockWorker(ctrl *gomock.Controller) *MockWorker {
	mock := &MockWorker{ctrl: ctrl}
	mock.recorder = &_MockWorkerRecorder{mock}
	return mock
}

func (_m *MockWorker) EXPECT() *_MockWorkerRecorder {
	return _m.recorder
}

func (_m *MockWorker) Work(_param0 int) {
	_m.ctrl.Call(_m, "Work", _param0)
}

func (_mr *_MockWorkerRecorder) Work(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Work", arg0)
}
