#!/bin/sh
# Mainly for documentation purposes and testing purposes

RABBIT_PORT=15672

curl -i -u guest:guest -H "content-type:application/json" -XPUT -d '{"type":"fanout","auto_delete":false,"durable":false,"internal":false,"arguments":{}}' http://localhost:$RABBIT_PORT/api/exchanges/%2f/buy-orders-theforge
curl -i -u guest:guest -H "content-type:application/json" -XPUT -d '{"type":"fanout","auto_delete":false,"durable":false,"internal":false,"arguments":{}}' http://localhost:$RABBIT_PORT/api/exchanges/%2f/buy-orders-domain
curl -i -u guest:guest -H "content-type:application/json" -XPUT -d '{"type":"fanout","auto_delete":false,"durable":false,"internal":false,"arguments":{}}' http://localhost:$RABBIT_PORT/api/exchanges/%2f/buy-orders-sinqlaison
curl -i -u guest:guest -H "content-type:application/json" -XPUT -d '{"type":"fanout","auto_delete":false,"durable":false,"internal":false,"arguments":{}}' http://localhost:$RABBIT_PORT/api/exchanges/%2f/buy-orders-heimatar

curl -i -u guest:guest -H "content-type:application/json" -XPUT -d '{"type":"fanout","auto_delete":false,"durable":false,"internal":false,"arguments":{}}' http://localhost:$RABBIT_PORT/api/exchanges/%2f/sell-orders-theforge
curl -i -u guest:guest -H "content-type:application/json" -XPUT -d '{"type":"fanout","auto_delete":false,"durable":false,"internal":false,"arguments":{}}' http://localhost:$RABBIT_PORT/api/exchanges/%2f/sell-orders-domain
curl -i -u guest:guest -H "content-type:application/json" -XPUT -d '{"type":"fanout","auto_delete":false,"durable":false,"internal":false,"arguments":{}}' http://localhost:$RABBIT_PORT/api/exchanges/%2f/sell-orders-sinqlaison
curl -i -u guest:guest -H "content-type:application/json" -XPUT -d '{"type":"fanout","auto_delete":false,"durable":false,"internal":false,"arguments":{}}' http://localhost:$RABBIT_PORT/api/exchanges/%2f/sell-orders-heimatar

curl -i -u guest:guest -H "content-type:application/json" -XPUT -d '{"type":"fanout","auto_delete":false,"durable":false,"internal":false,"arguments":{}}' http://localhost:$RABBIT_PORT/api/exchanges/%2f/buy-orders-all
curl -i -u guest:guest -H "content-type:application/json" -XPUT -d '{"type":"fanout","auto_delete":false,"durable":false,"internal":false,"arguments":{}}' http://localhost:$RABBIT_PORT/api/exchanges/%2f/sell-orders-all

curl -i -u guest:guest -H "content-type:application/json" -XPUT -d '{"type":"fanout","auto_delete":false,"durable":false,"internal":false,"arguments":{}}' http://localhost:$RABBIT_PORT/api/exchanges/%2f/orders-all

curl -i -u guest:guest -H "content-type:application/json" -XPOST http://localhost:$RABBIT_PORT/api/bindings/%2f/e/buy-orders-theforge/e/buy-orders-all
curl -i -u guest:guest -H "content-type:application/json" -XPOST http://localhost:$RABBIT_PORT/api/bindings/%2f/e/buy-orders-domain/e/buy-orders-all
curl -i -u guest:guest -H "content-type:application/json" -XPOST http://localhost:$RABBIT_PORT/api/bindings/%2f/e/buy-orders-sinqlaison/e/buy-orders-all
curl -i -u guest:guest -H "content-type:application/json" -XPOST http://localhost:$RABBIT_PORT/api/bindings/%2f/e/buy-orders-heimatar/e/buy-orders-all

curl -i -u guest:guest -H "content-type:application/json" -XPOST http://localhost:$RABBIT_PORT/api/bindings/%2f/e/sell-orders-theforge/e/sell-orders-all
curl -i -u guest:guest -H "content-type:application/json" -XPOST http://localhost:$RABBIT_PORT/api/bindings/%2f/e/sell-orders-domain/e/sell-orders-all
curl -i -u guest:guest -H "content-type:application/json" -XPOST http://localhost:$RABBIT_PORT/api/bindings/%2f/e/sell-orders-sinqlaison/e/sell-orders-all
curl -i -u guest:guest -H "content-type:application/json" -XPOST http://localhost:$RABBIT_PORT/api/bindings/%2f/e/sell-orders-heimatar/e/sell-orders-all

curl -i -u guest:guest -H "content-type:application/json" -XPOST http://localhost:$RABBIT_PORT/api/bindings/%2f/e/buy-orders-all/e/orders-all
curl -i -u guest:guest -H "content-type:application/json" -XPOST http://localhost:$RABBIT_PORT/api/bindings/%2f/e/sell-orders-all/e/orders-all